### ISSUE TITLE
Switch to AndroidX

### ISSUE THREAD

**Issue by zimmi** [nishkarsh/android-permissions#14]
Thank you for this amazing library, it helps escaping the tyranny of the activity lifecycle!

I'm using `android.useAndroidX=true` and `android.enableJetifier=true` in the `gradle.properties` of my app which leads to an exception (see below). To avoid this, I had to add `implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0'` to my `gradle.build` file.

Because [AndroidX replaces the now unmaintained Support Library](https://developer.android.com/jetpack/androidx), I think the time is right to switch to AndroidX, adding the correct localbroadcastmanager-dependency to android-permissions while doing so. Would you accept a PR doing this?

I see that [LocalBroadcastManager itself is deprecated](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/localbroadcastmanager/src/main/java/androidx/localbroadcastmanager/content/LocalBroadcastManager.java#48), but there is no direct replacement and the AndroidX version isn't going anywhere, so I'd leave the code alone for now, just add the dependency.

The original exception:
```
2019-10-27 17:40:29.273 28731-28731/org.example.myapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.example.myapp, PID: 28731
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/localbroadcastmanager/content/LocalBroadcastManager;
        at com.intentfilter.androidpermissions.PermissionManager.registerBroadcastReceiver(PermissionManager.java:90)
        at com.intentfilter.androidpermissions.PermissionHandler.registerForBroadcastIfNeeded(PermissionHandler.java:130)
        at com.intentfilter.androidpermissions.PermissionHandler.checkPermissions(PermissionHandler.java:46)
        at com.intentfilter.androidpermissions.PermissionManager.checkPermissions(PermissionManager.java:53)
        at org.example.myapp.LocationLiveData.onActive(MainViewModel.kt:50)
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:437)
        at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:395)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:129)
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:205)
        at androidx.lifecycle.ReportFragment.onStart(ReportFragment.java:170)
        at android.app.Fragment.performStart(Fragment.java:2548)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1334)
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1576)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1637)
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3046)
        at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3003)
        at android.app.FragmentController.dispatchStart(FragmentController.java:193)
        at android.app.Activity.performStart(Activity.java:7165)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2952)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6729)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.localbroadcastmanager.content.LocalBroadcastManager" on path: DexPathList[[zip file "/data/app/org.example.myapp-LZugZ-nCgbUhyoEE1G9AWA==/base.apk"],nativeLibraryDirectories=[/data/app/org.example.myapp-LZugZ-nCgbUhyoEE1G9AWA==/lib/arm64, /data/app/org.example.myapp-LZugZ-nCgbUhyoEE1G9AWA==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.intentfilter.androidpermissions.PermissionManager.registerBroadcastReceiver(PermissionManager.java:90) 
        at com.intentfilter.androidpermissions.PermissionHandler.registerForBroadcastIfNeeded(PermissionHandler.java:130) 
        at com.intentfilter.androidpermissions.PermissionHandler.checkPermissions(PermissionHandler.java:46) 
        at com.intentfilter.androidpermissions.PermissionManager.checkPermissions(PermissionManager.java:53) 
        at org.example.myapp.LocationLiveData.onActive(MainViewModel.kt:50) 
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:437) 
        at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:395) 
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361) 
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300) 
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339) 
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145) 
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131) 
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:129) 
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:205) 
        at androidx.lifecycle.ReportFragment.onStart(ReportFragment.java:170) 
        at android.app.Fragment.performStart(Fragment.java:2548) 
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1334) 
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1576) 
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1637) 
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3046) 
        at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3003) 
        at android.app.FragmentController.dispatchStart(FragmentController.java:193) 
        at android.app.Activity.performStart(Activity.java:7165) 
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2952) 
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180) 
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:198) 
        at android.app.ActivityThread.main(ActivityThread.java:6729) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by nishkarsh** [comment]
Hey @zimmi!

Thanks for reporting this. It does make sense to me to switch to the libraries that are part of the jetpack. As I am currently not available to work on this, I would highly appreciate the PR for this. Thanks!

**Comment by zimmi** [comment]
Thank you for the quick answer, @nishkarsh! I'll see what I can do.
