### ISSUE TITLE
NPE on runningAppProcesses iterator() in AppStatus.isInForeground() method

### ISSUE THREAD

**Issue by hatched-mariusz** [nishkarsh/android-permissions#21]
#### Bug Report

* Steps to reproduce the problem (include logs and/or sample code where appropriate):
N/A crash from crashlitics:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
       at com.intentfilter.androidpermissions.helpers.AppStatus.isInForeground(AppStatus.java:18)
       at com.intentfilter.androidpermissions.PermissionHandler.requestPermissions(PermissionHandler.java:74)
       at com.intentfilter.androidpermissions.PermissionHandler.checkPermissions(PermissionHandler.java:50)
       at com.intentfilter.androidpermissions.PermissionManager.checkPermissions(PermissionManager.java:52)
       at com.hatchedlabs.commons.permission.PermissionsHelper.checkPermissions(PermissionsHelper.java:32)
```

* Android API Version: Version:Android 9 Pie - 28
* Android Device (include Model and Manufacturer): https://www.gsmarena.com/blu_view_1-9994.php 
* Link to sample code (not always needed): 
https://github.com/nishkarsh/android-permissions/blob/master/src/main/java/com/intentfilter/androidpermissions/helpers/AppStatus.java

```
//FIX
if (runningAppProcesses == null) 
    return false 
```

**Comment by mariopce** [comment]
bump 👍

**Comment by hatched-mariusz** [comment]
bump ⬆️

**Comment by nishkarsh** [comment]
Hello folks! I know this is pending for long, I should be able to get the required changed merged and tested over the weekend.

**Comment by hatched-mariusz** [comment]
issue fixed
